#include "CkStructTypeSelector_K2NodeHelpers.h"

#include "CkCore/Validation/CkIsValid.h"

#include <EdGraphSchema_K2.h>

// --------------------------------------------------------------------------------------------------------------------

auto ck::FStructTypeSelectorHelpers::CreateSelectorPin(
    UEdGraphNode& InNode,
    FName InPinName,
    UScriptStruct* InBaseStructFilter) -> UEdGraphPin*
{
    auto* Pin = InNode.CreatePin(
        EGPD_Input,
        UEdGraphSchema_K2::PC_Struct,
        FCk_StructTypeSelector::StaticStruct(),
        InPinName
    );

    Pin->bNotConnectable = true;
    Pin->bDefaultValueIsIgnored = false;
    Pin->bHidden = false;

    // Store the filter path in AutogeneratedDefaultValue — survives reconstruction,
    // doesn't affect pin type matching or value serialization
    if (ck::IsValid(InBaseStructFilter, ck::IsValid_Policy_NullptrOnly{}))
    {
        Pin->AutogeneratedDefaultValue = InBaseStructFilter->GetPathName();
    }

    return Pin;
}

// --------------------------------------------------------------------------------------------------------------------

auto ck::FStructTypeSelectorHelpers::GetSelectedStruct(
    const UEdGraphNode& InNode,
    FName InPinName) -> UScriptStruct*
{
    auto* Pin = InNode.FindPin(InPinName);
    if (ck::Is_NOT_Valid(Pin, ck::IsValid_Policy_NullptrOnly{}))
    { return nullptr; }

    const auto& DefaultValue = Pin->GetDefaultAsString();
    if (DefaultValue.IsEmpty())
    { return nullptr; }

    const auto* StructType = FCk_StructTypeSelector::StaticStruct();

    auto SelectorValue = FCk_StructTypeSelector{};
    StructType->ImportText(*DefaultValue, &SelectorValue, nullptr, PPF_None, GLog, StructType->GetName());

    return SelectorValue.Get_StructType();
}

// --------------------------------------------------------------------------------------------------------------------

auto ck::FStructTypeSelectorHelpers::GetBaseStructFilter(
    const UEdGraphPin& InPin) -> UScriptStruct*
{
    const auto& FilterPath = InPin.AutogeneratedDefaultValue;
    if (FilterPath.IsEmpty())
    { return nullptr; }

    return FindObject<UScriptStruct>(nullptr, *FilterPath);
}

// --------------------------------------------------------------------------------------------------------------------
