#pragma once

// ====================================================================================================================
// GENERATED FILE — DO NOT HAND-EDIT.
// Generated by Source/CkScripts/Generate-CkIcons.ps1 from Resources/Icons/CkIcons_Manifest.json.
// To add or change an icon: edit the manifest (and vendor the SVG via Import-MdiIcon.ps1), then regenerate.
// ====================================================================================================================

#include "CkCore/Format/CkFormat.h"

#include <CoreMinimal.h>

#include "CkIcons_Generated.generated.h"

// --------------------------------------------------------------------------------------------------------------------

UENUM(BlueprintType)
enum class ECk_Icon : uint8
{
    Delete,
    Entity,
    Error,
    Filter,
    Fragment,
    Info,
    Pin,
    Processor,
    Refresh,
    Save,
    Search,
    Success,
    Timer,
    Visibility,
    Warning,
};

CK_DEFINE_CUSTOM_FORMATTER_ENUM(ECk_Icon);

// --------------------------------------------------------------------------------------------------------------------

namespace ck::icons
{
    struct FGeneratedEntry
    {
        ECk_Icon Icon;
        const TCHAR* SemanticName;
        const TCHAR* RelativePath;
    };

    CKEDITORTOOLS_API auto Get_GeneratedEntries() -> TConstArrayView<FGeneratedEntry>;
}

// --------------------------------------------------------------------------------------------------------------------
