#pragma once

// ====================================================================================================================
// GENERATED FILE — DO NOT HAND-EDIT.
// Generated by Source/CkScripts/Generate-CkIcons.ps1 from Resources/Icons/CkIcons_Manifest.json.
// To add or change an icon: edit the manifest (and vendor the SVG via Import-MdiIcon.ps1), then regenerate.
// ====================================================================================================================

#include "CkCore/Format/CkFormat.h"

#include <CoreMinimal.h>

#include "CkIcons_Generated.generated.h"

// --------------------------------------------------------------------------------------------------------------------

UENUM(BlueprintType)
enum class ECk_Icon : uint8
{
    // "no icon" — carriers default to this; the registry returns nullptr for it without complaint.
    None UMETA(Hidden),

    Actor,
    ActorBridge,
    Aggro,
    Aim,
    Anchored,
    AStar,
    Attribute,
    AttributeByte,
    AttributeFloat,
    AttributeInteger,
    AttributeRotator,
    AttributeVector,
    Audio,
    BodyActivity,
    Broadcast,
    Camera,
    Capture,
    Catalog,
    Channel,
    Cinematic,
    Cleanup,
    Combat,
    Compass,
    Connection,
    Copy,
    Crowd,
    Currency,
    CycleRoot,
    DayTime,
    DefinitionBuilt,
    Delete,
    Destructive,
    Diagnostics,
    Dialog,
    DirtyPackages,
    Display,
    Door,
    Dormant,
    Duplicates,
    Edit,
    Entity,
    EntityCollection,
    EntityInfo,
    Eqs,
    Error,
    Experiment,
    Filter,
    Fix,
    FogOfWar,
    Foliage,
    Fragment,
    FrameActor,
    Freeze,
    Gate,
    Goap,
    Grab,
    Grid,
    Hardware,
    HotPath,
    Info,
    Input,
    Interaction,
    Inventory,
    IsmRenderer,
    Jolt,
    Label,
    Lighting,
    Loadout,
    Locked,
    Log,
    MaterialAsset,
    Media,
    Microphone,
    Minimap,
    Network,
    Note,
    Objective,
    Orphaned,
    OverlapBody,
    PathNetwork,
    PathNetworkFollower,
    Payload,
    Physics,
    Pin,
    Play,
    Power,
    Precision,
    Probe,
    Processor,
    ProfileTiming,
    Projectile,
    Protection,
    Rail,
    Rarity,
    Recording,
    Redirectors,
    Refresh,
    Relationships,
    Report,
    Resolver,
    Ring,
    RuntimeSpawned,
    Save,
    SaveKey,
    SaveSlot,
    SceneNode,
    Schedule,
    Screen,
    Search,
    SelectInViewport,
    Settings,
    Shapes,
    Signal,
    Size,
    SkipBackward,
    SkipForward,
    Speaker,
    StateMachine,
    Storage,
    Success,
    Target,
    TextureAsset,
    Ticket,
    Timer,
    Transform,
    Tween,
    UIWindow,
    Variables,
    Vehicle,
    Vfx,
    ViewBack,
    ViewBottom,
    ViewFront,
    ViewLeft,
    ViewPerspective,
    ViewRight,
    ViewTop,
    Visibility,
    Waiting,
    Warning,
    Web,
    Well,
    Wind,
    World,
};

CK_DEFINE_CUSTOM_FORMATTER_ENUM(ECk_Icon);

// --------------------------------------------------------------------------------------------------------------------

namespace ck::icons
{
    struct FGeneratedEntry
    {
        ECk_Icon Icon;
        const TCHAR* SemanticName;
        const TCHAR* RelativePath;
    };

    CKEDITORTOOLS_API auto Get_GeneratedEntries() -> TConstArrayView<FGeneratedEntry>;

    // The decorative pool: stable hash-picked variety glyphs for archetypes without a bespoke icon.
    CKEDITORTOOLS_API auto Get_GeneratedPool() -> TConstArrayView<ECk_Icon>;
}

// --------------------------------------------------------------------------------------------------------------------
