#include "CkIcons_Generated.h"

// ====================================================================================================================
// GENERATED FILE — DO NOT HAND-EDIT.
// Generated by Source/CkScripts/Generate-CkIcons.ps1 from Resources/Icons/CkIcons_Manifest.json.
// To add or change an icon: edit the manifest (and vendor the SVG via Import-MdiIcon.ps1), then regenerate.
// ====================================================================================================================

namespace ck::icons
{
    auto
        Get_GeneratedEntries()
        -> TConstArrayView<FGeneratedEntry>
    {
        static const FGeneratedEntry Entries[] =
        {
            { ECk_Icon::Delete, TEXT("Delete"), TEXT("Mdi/delete-outline") },
            { ECk_Icon::Entity, TEXT("Entity"), TEXT("Mdi/cube-outline") },
            { ECk_Icon::Error, TEXT("Error"), TEXT("Mdi/alert-circle-outline") },
            { ECk_Icon::Filter, TEXT("Filter"), TEXT("Mdi/filter-outline") },
            { ECk_Icon::Fragment, TEXT("Fragment"), TEXT("Mdi/puzzle-outline") },
            { ECk_Icon::Info, TEXT("Info"), TEXT("Mdi/information-outline") },
            { ECk_Icon::Pin, TEXT("Pin"), TEXT("Mdi/pin-outline") },
            { ECk_Icon::Processor, TEXT("Processor"), TEXT("Mdi/cog-outline") },
            { ECk_Icon::Refresh, TEXT("Refresh"), TEXT("Mdi/refresh") },
            { ECk_Icon::Save, TEXT("Save"), TEXT("Mdi/content-save-outline") },
            { ECk_Icon::Search, TEXT("Search"), TEXT("Mdi/magnify") },
            { ECk_Icon::Success, TEXT("Success"), TEXT("Mdi/check-circle-outline") },
            { ECk_Icon::Timer, TEXT("Timer"), TEXT("Mdi/timer-outline") },
            { ECk_Icon::Visibility, TEXT("Visibility"), TEXT("Mdi/eye-outline") },
            { ECk_Icon::Warning, TEXT("Warning"), TEXT("Mdi/alert-outline") },
        };

        return Entries;
    }
}

// --------------------------------------------------------------------------------------------------------------------
