using System;
using System.Diagnostics;
using System.IO;
using UnrealBuildTool;

public class CkWatermark : CkModuleRules
{
    public CkWatermark(ReadOnlyTargetRules Target) : base(Target)
    {
        PublicIncludePaths.AddRange(
            new string[] {
                // ... add public include paths required here ...
            }
            );

        PrivateIncludePaths.AddRange(
            new string[] {
                // ... add other private include paths required here ...
            }
            );

        PublicDependencyModuleNames.AddRange(
            new string[]
            {
                "Core",
                "CommonUI",
                "CoreUObject",
                "Engine",
                "Slate",
                "SlateCore",
                "UMG",
                "CkCore",
                "CkUI",
                "CkMemory",
                "CkEcs",
                "GameplayTags",
                // ... add other public dependencies that you statically link with here ...
            }
            );

        PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "DeveloperSettings",
                "CkSettings",
                // ... add private dependencies that you statically link with here ...
            }
            );

        // Determine the repo root: prefer the .uproject directory so the hashes
        // reflect the BusterBlock project, not the CkFoundation submodule.
        // Fall back to walking 4 levels up from Source/CkWatermark/ if
        // Target.ProjectFile is unavailable (e.g., engine-tool builds).
        string repoDir = (Target.ProjectFile != null)
            ? Target.ProjectFile.Directory.FullName
            : Path.GetFullPath(Path.Combine(ModuleDirectory, "..", "..", "..", ".."));

        GenerateBuildIdHeader(ModuleDirectory, repoDir);
    }

    // Reference branches to compute merge-bases against.
    // Extend this list to add more branches; Build.cs tries each local name
    // first then falls back to origin/<name>.
    private static readonly string[] s_ReferenceBranches = { "dev", "develop", "main", "master", "demo", "release" };

    // -------------------------------------------------------------------------
    // Bakes the project's git hashes into a constexpr header so the shipped
    // binary can display them without needing git at runtime.
    // Designed to be failure-safe: any exception falls through to writing
    // "unknown" so a missing git binary or read-only source tree never breaks
    // the compile.
    // -------------------------------------------------------------------------

    private static void GenerateBuildIdHeader(string ModuleDir, string RepoDir)
    {
        string head = "unknown";
        var branchNames  = new System.Collections.Generic.List<string>();
        var branchHashes = new System.Collections.Generic.List<string>();

        try
        {
            head = RunGit(RepoDir, "rev-parse --short HEAD") ?? "unknown";

            foreach (string branch in s_ReferenceBranches)
            {
                // Try the local branch first, then the remote tracking branch.
                string fullBase = RunGit(RepoDir, "merge-base HEAD " + branch)
                               ?? RunGit(RepoDir, "merge-base HEAD origin/" + branch);
                string hash = (fullBase != null)
                    ? (RunGit(RepoDir, "rev-parse --short " + fullBase.Trim()) ?? "unknown")
                    : "unknown";
                branchNames.Add(branch);
                branchHashes.Add(hash);
            }
        }
        catch { /* git unavailable — fall through to write "unknown" for all entries */ }

        // Fill any entries that didn't make it through the try block.
        while (branchNames.Count < s_ReferenceBranches.Length)
        {
            branchNames.Add(s_ReferenceBranches[branchNames.Count]);
            branchHashes.Add("unknown");
        }

        int branchCount = branchNames.Count;

        var quotedNames  = new System.Collections.Generic.List<string>();
        var quotedHashes = new System.Collections.Generic.List<string>();
        foreach (string n in branchNames)  quotedNames.Add("\"" + n + "\"");
        foreach (string h in branchHashes) quotedHashes.Add("\"" + h + "\"");

        string namesArray  = string.Join(", ", quotedNames.ToArray());
        string hashesArray = string.Join(", ", quotedHashes.ToArray());

        string outDir  = Path.Combine(ModuleDir, "Public", "CkWatermark", "Generated");
        string outPath = Path.Combine(outDir, "CkWatermark_BuildId.h");
        string content =
            "// Auto-generated by CkWatermark.Build.cs \u2014 do not edit.\n"
          + "#pragma once\n\n"
          + "namespace CkWatermarkBuildId\n{\n"
          + "    constexpr const char* HeadHash = \"" + head.Trim() + "\";\n\n"
          + "    constexpr int         BranchCount           = " + branchCount + ";\n"
          + "    constexpr const char* BranchNames["     + branchCount + "]     = { " + namesArray  + " };\n"
          + "    constexpr const char* MergeBaseHashes[" + branchCount + "] = { " + hashesArray + " };\n"
          + "}\n";

        try
        {
            Directory.CreateDirectory(outDir);
            // Only rewrite when content changes to avoid unnecessary recompilation.
            if (!File.Exists(outPath) || File.ReadAllText(outPath) != content)
                File.WriteAllText(outPath, content);
        }
        catch { /* silently ignore write failure — header may exist from a prior build */ }
    }

    private static string RunGit(string WorkDir, string Args)
    {
        try
        {
            var psi = new ProcessStartInfo("git", Args)
            {
                WorkingDirectory       = WorkDir,
                RedirectStandardOutput = true,
                RedirectStandardError  = true,
                UseShellExecute        = false,
                CreateNoWindow         = true,
            };
            using (var proc = Process.Start(psi))
            {
                if (proc == null) return null;
                proc.WaitForExit(3000);
                return proc.ExitCode == 0 ? proc.StandardOutput.ReadToEnd().Trim() : null;
            }
        }
        catch { return null; }
    }
}
