using System;
using System.Diagnostics;
using System.IO;
using UnrealBuildTool;

public class CkWatermark : CkModuleRules
{
    public CkWatermark(ReadOnlyTargetRules Target) : base(Target)
    {
        PublicIncludePaths.AddRange(
            new string[] {
                // ... add public include paths required here ...
            }
            );

        PrivateIncludePaths.AddRange(
            new string[] {
                // ... add other private include paths required here ...
            }
            );

        PublicDependencyModuleNames.AddRange(
            new string[]
            {
                "Core",
                "CommonUI",
                "CoreUObject",
                "Engine",
                "Slate",
                "SlateCore",
                "UMG",
                "CkCore",
                "CkUI",
                "CkMemory",
                "CkEcs",
                "GameplayTags",
                // ... add other public dependencies that you statically link with here ...
            }
            );

        PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "DeveloperSettings",
                "CkSettings",
                // ... add private dependencies that you statically link with here ...
            }
            );

        // Determine the repo root: prefer the .uproject directory so the hashes
        // reflect the BusterBlock project, not the CkFoundation submodule.
        // Fall back to walking 4 levels up from Source/CkWatermark/ if
        // Target.ProjectFile is unavailable (e.g., engine-tool builds).
        string repoDir = (Target.ProjectFile != null)
            ? Target.ProjectFile.Directory.FullName
            : Path.GetFullPath(Path.Combine(ModuleDirectory, "..", "..", "..", ".."));

        GenerateBuildIdHeader(ModuleDirectory, repoDir);
    }

    // -------------------------------------------------------------------------
    // Bakes the project's git hashes into a constexpr header so the shipped
    // binary can display them without needing git at runtime.
    // Designed to be failure-safe: any exception falls through to writing
    // "unknown" so a missing git binary or read-only source tree never breaks
    // the compile.
    // -------------------------------------------------------------------------

    private static void GenerateBuildIdHeader(string ModuleDir, string RepoDir)
    {
        string head     = "unknown";
        string baseHash = "unknown";

        try
        {
            head = RunGit(RepoDir, "rev-parse --short HEAD") ?? "unknown";

            string fullBase = RunGit(RepoDir, "merge-base HEAD dev")
                           ?? RunGit(RepoDir, "merge-base HEAD origin/dev");

            baseHash = (fullBase != null)
                ? (RunGit(RepoDir, "rev-parse --short " + fullBase.Trim()) ?? "unknown")
                : "unknown";
        }
        catch { /* git unavailable — fall through to write "unknown" */ }

        string outDir  = Path.Combine(ModuleDir, "Public", "CkWatermark", "Generated");
        string outPath = Path.Combine(outDir, "CkWatermark_BuildId.h");
        string content =
            "// Auto-generated by CkWatermark.Build.cs \u2014 do not edit.\n"
          + "#pragma once\n\n"
          + "namespace CkWatermarkBuildId\n{\n"
          + "    constexpr const char* HeadHash      = \"" + head.Trim()     + "\";\n"
          + "    constexpr const char* MergeBaseHash = \"" + baseHash.Trim() + "\";\n"
          + "}\n";

        try
        {
            Directory.CreateDirectory(outDir);
            // Only rewrite when content changes to avoid unnecessary recompilation.
            if (!File.Exists(outPath) || File.ReadAllText(outPath) != content)
                File.WriteAllText(outPath, content);
        }
        catch { /* silently ignore write failure — header may exist from a prior build */ }
    }

    private static string RunGit(string WorkDir, string Args)
    {
        try
        {
            var psi = new ProcessStartInfo("git", Args)
            {
                WorkingDirectory       = WorkDir,
                RedirectStandardOutput = true,
                RedirectStandardError  = true,
                UseShellExecute        = false,
                CreateNoWindow         = true,
            };
            using (var proc = Process.Start(psi))
            {
                if (proc == null) return null;
                proc.WaitForExit(3000);
                return proc.ExitCode == 0 ? proc.StandardOutput.ReadToEnd().Trim() : null;
            }
        }
        catch { return null; }
    }
}
