#pragma once

#include "CkGoap_Fragment_Data.h"
#include "CkGoap/Bundle/CkGoap_Bundle_Fragment_Data.h"

#include "CkEcs/Handle/CkHandle.h"

#include "CkGoap_Utils.generated.h"

// ====================================================================================================================

class UCk_GoapAction_EntityScript;

// ====================================================================================================================
// Root-level GOAP utils. Bundle / Tier specific verbs live in:
//   Bundle/CkGoap_Bundle_Utils.h  (UCk_Utils_Goap_Bundle_UE)
//   Tier/CkGoap_Tier_Utils.h      (UCk_Utils_Goap_Tier_UE)
// ====================================================================================================================

UCLASS(NotBlueprintable, Meta = (ScriptMixin = "FCk_Handle_Goap"))
class CKGOAP_API UCk_Utils_Goap_UE : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	CK_GENERATED_BODY(UCk_Utils_Goap_UE);
	CK_DEFINE_CPP_CASTCHECKED_TYPESAFE(FCk_Handle_Goap);

public:
	// Construct a GOAP root container on InOwner. One per owner. The root
	// holds RecordOfGoapBundles; AddBundle (Bundle/CkGoap_Bundle_Utils.h)
	// installs each bundle as a record entry.
	UFUNCTION(BlueprintCallable, Category = "Ck|Utils|Goap",
		DisplayName = "[Ck][Goap] Add")
	static FCk_Handle_Goap
	Add(
		UPARAM(ref) FCk_Handle& InOwner,
		const FCk_Fragment_Goap_RootParamsData& InParams);

	UFUNCTION(BlueprintCallable, Category = "Ck|Utils|Goap",
		DisplayName = "[Ck][Goap] Has")
	static bool
	Has(const FCk_Handle& InHandle);

	// AS-side typesafe casts are not exposed as a UFUNCTION named `Cast`
	// because `Cast` is a reserved AngelScript keyword. C++ consumers use
	// `UCk_Utils_Goap_UE::CastChecked(...)` directly (macro-generated by
	// CK_DEFINE_CPP_CASTCHECKED_TYPESAFE). AS consumers get typed handles
	// back from Add / AddBundle / AddTier and Find_Bundle / Find_Tier — no
	// need for a global cast.

	UFUNCTION(BlueprintCallable, Category = "Ck|Utils|Goap",
		DisplayName = "[Ck][Goap] Find Bundle")
	static FCk_Handle_Goap_Bundle
	Find_Bundle(
		const FCk_Handle_Goap& InGoap,
		FGameplayTag InBundleTag);
};
