#pragma once

#include "CkGoap_Fragment_Data.h"
#include "CkGoap/ActionSet/CkGoap_ActionSet_Fragment_Data.h"

#include "CkEcs/Handle/CkHandle.h"

#include "CkGoap_Utils.generated.h"

// ====================================================================================================================

class UCk_GoapAction_EntityScript;

// ====================================================================================================================
// Root-level GOAP utils. ActionSet / Action specific verbs live in:
//   ActionSet/CkGoap_ActionSet_Utils.h  (UCk_Utils_Goap_ActionSet_UE)
//   Action/CkGoap_Action_Utils.h        (UCk_Utils_Goap_Action_UE)
// ====================================================================================================================

UCLASS(NotBlueprintable, Meta = (ScriptMixin = "FCk_Handle_Goap"))
class CKGOAP_API UCk_Utils_Goap_UE : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	CK_GENERATED_BODY(UCk_Utils_Goap_UE);
	CK_DEFINE_CPP_CASTCHECKED_TYPESAFE(FCk_Handle_Goap);

public:
	// Construct a GOAP root container on InOwner. One per owner. The root
	// holds RecordOfGoapActionSets; AddActionSet (ActionSet/CkGoap_ActionSet_Utils.h)
	// installs each ActionSet as a record entry.
	UFUNCTION(BlueprintCallable, Category = "Ck|Utils|Goap",
		DisplayName = "[Ck][Goap] Add")
	static FCk_Handle_Goap
	Add(
		UPARAM(ref) FCk_Handle& InOwner,
		const FCk_Fragment_Goap_RootParamsData& InParams);

	UFUNCTION(BlueprintCallable, Category = "Ck|Utils|Goap",
		DisplayName = "[Ck][Goap] Has")
	static bool
	Has(const FCk_Handle& InHandle);

	// AS-side typesafe casts are not exposed as a UFUNCTION named `Cast`
	// because `Cast` is a reserved AngelScript keyword. C++ consumers use
	// `UCk_Utils_Goap_UE::CastChecked(...)` directly (macro-generated by
	// CK_DEFINE_CPP_CASTCHECKED_TYPESAFE). AS consumers get typed handles
	// back from Add / AddActionSet / AddAction_ToActionSet and Find_ActionSet / Find_Action — no
	// need for a global cast.

	UFUNCTION(BlueprintCallable, Category = "Ck|Utils|Goap",
		DisplayName = "[Ck][Goap] Find ActionSet")
	static FCk_Handle_Goap_ActionSet
	Find_ActionSet(
		const FCk_Handle_Goap& InGoap,
		FGameplayTag InActionSetTag);
};
