#!/usr/bin/env bash
# P3 Track-A bulk rename: applies rename-map.tsv (module<TAB>old<TAB>new) across all code trees
# and emits the CoreRedirects snippet. Run from the CkPlugins superproject root via Git Bash:
#   bash Plugins/CkFoundation/docs/campaigns/spec-fragment-granularity/apply-rename.sh
# Idempotent: re-running is a no-op once no old names remain.
set -euo pipefail

ROOT="$(pwd)"
MAP="Plugins/CkFoundation/docs/campaigns/spec-fragment-granularity/rename-map.tsv"
INI_SNIPPET="Plugins/CkFoundation/docs/campaigns/spec-fragment-granularity/generated-redirects.ini"

[[ -f "$MAP" ]] || { echo "run from CkPlugins root; $MAP not found" >&2; exit 1; }

# 1. Collect candidate files once: every file that mentions ParamsData or ConstructionInfo in the
#    swept trees (hand-written code only — Script/Generated regenerates, docs/ are archives).
mapfile -t FILES < <(rg --no-ignore -l "ParamsData|EntityReplicationDriver_ConstructionInfo" \
    --glob '!**/Script/Generated/**' --glob '!**/Saved/**' --glob '!**/Intermediate/**' \
    --glob '!**/docs/**' --glob '!**/*.md' --glob '!**/*.uasset' --glob '!**/*.umap' \
    Plugins/CkFoundation/Source Plugins/CkFoundation/Script Plugins/CkFoundation/Config \
    Plugins/CkTests Plugins/CkGameplayDebugger Script 2>/dev/null || true)

echo "files to sweep: ${#FILES[@]}"

# 2. Build one sed program, longest old-name first (paranoia against prefix overlap).
SED_PROG="$(sort -t$'\t' -k2,2 "$MAP" | awk -F'\t' '{print length($2) "\t" $2 "\t" $3}' \
    | sort -rn | awk -F'\t' '{print "s/\\b" $2 "\\b/" $3 "/g"}')"

for f in "${FILES[@]}"; do
    sed -i "$SED_PROG" "$f"
done

# 3. Emit CoreRedirects snippet (reflection names drop the leading F).
{
  echo "; Generated by apply-rename.sh — append to [CoreRedirects] in DefaultCkFoundation.ini"
  awk -F'\t' '{
    old=$2; new=$3; sub(/^F/, "", old); sub(/^F/, "", new);
    printf "+StructRedirects=(OldName=\"/Script/%s.%s\",NewName=\"/Script/%s.%s\")\n", $1, old, $1, new;
  }' "$MAP"
} > "$INI_SNIPPET"

echo "redirect snippet: $INI_SNIPPET ($(wc -l < "$INI_SNIPPET") lines)"

# 4. Verify no old names remain in code trees.
LEFT=$(rg --no-ignore -l "FCk_[A-Za-z0-9_]*ParamsData|FCk_EntityReplicationDriver_ConstructionInfo" \
    --glob '!**/Script/Generated/**' --glob '!**/Saved/**' --glob '!**/Intermediate/**' \
    --glob '!**/docs/**' --glob '!**/*.md' \
    Plugins/CkFoundation/Source Plugins/CkFoundation/Script \
    Plugins/CkTests Plugins/CkGameplayDebugger Script 2>/dev/null | wc -l)
echo "files still containing old names (expect 0): $LEFT"
