#include "CkScriptProcessorDriverGenerator.h"

#include "CkAngelscriptGenerator/CkAngelscriptGenerator_Log.h"
#include "CkAngelscriptGenerator/CkAngelscriptGenerator_RegenOwnership.h"

#include "CkCore/Format/CkFormat.h"
#include "CkCore/Reflection/CkReflection_Utils.h"
#include "CkCore/Time/CkTime.h"
#include "CkCore/Validation/CkIsValid.h"

#include "CkEcs/Handle/CkHandle.h"
#include "CkEcs/Processor/CkProcessor_Script.h"

#include <HAL/FileManager.h>
#include <Interfaces/IPluginManager.h>
#include <Misc/App.h>
#include <Misc/FileHelper.h>
#include <Misc/Paths.h>
#include <UObject/Class.h>
#include <UObject/UObjectIterator.h>

#if WITH_ANGELSCRIPT_CK
#include "ClassGenerator/ASClass.h"   // UASClass + FAngelscriptManager + angelscript.h (asITypeInfo/asIScriptFunction/asTM_*)
#endif

// --------------------------------------------------------------------------------------------------------------------

#if WITH_EDITOR

namespace ck::scriptprocessor_driver_generator
{
    static const TCHAR* GFileHeader =
        TEXT("// GENERATED by CkScriptProcessorDriverGenerator — DO NOT EDIT. Regenerated on AS compile.\n")
        TEXT("// One <Dev>_Driver per typed script processor: ForEachBatch loops the native join and forwards each\n")
        TEXT("// element to the dev class's ForEachEntity. Signature discovery is via AS-VM reflection.\n")
        TEXT("\n");

    static const auto GDriverSuffix = FString{TEXT("_Driver")};
    static const auto GGeneratedDirSegment = FString{TEXT("/Script/Generated/")};

    // ----------------------------------------------------------------------------------------------------------------

    struct FForEachParam
    {
        UScriptStruct* _Struct  = nullptr;
        bool           _IsConst = false;   // const& -> ReadOnly
        bool           _IsRef   = false;   // reference (any direction); false => by-value
    };

    struct FSignature
    {
        bool                  _HasHandleParam = false;
        TArray<FForEachParam> _FragmentParams;
        FString               _Error;   // non-empty => invalid signature; text names the violation
    };

    // ----------------------------------------------------------------------------------------------------------------
    // Reflect the plain (non-UFUNCTION) ForEachEntity method's parameters via the AS type system. Returns empty when
    // InClass is not an AS class or has no ForEachEntity method (i.e. it is not a typed processor).

    auto
    Reflect_ForEachEntityParams(
        UClass* InClass)
        -> TArray<FForEachParam>
    {
        auto Result = TArray<FForEachParam>{};

#if WITH_ANGELSCRIPT_CK
        auto* ASClass = Cast<UASClass>(InClass);
        if (ASClass == nullptr || ASClass->ScriptTypePtr == nullptr)
        { return Result; }

        auto* ScriptType = static_cast<asITypeInfo*>(ASClass->ScriptTypePtr);
        if (ScriptType == nullptr)
        { return Result; }

        static const char* const MethodName = "ForEachEntity";

        auto* Method = ScriptType->GetMethodByName(MethodName);
        if (Method == nullptr)
        {
            // GetMethodByName returns null for an overloaded name — disambiguate by scanning.
            for (asUINT Index = 0, Count = ScriptType->GetMethodCount(); Index < Count; ++Index)
            {
                auto* Candidate = ScriptType->GetMethodByIndex(Index);
                if (Candidate != nullptr && FCStringAnsi::Strcmp(Candidate->GetName(), MethodName) == 0)
                {
                    Method = Candidate;
                    break;
                }
            }
        }
        if (Method == nullptr)
        { return Result; }

        auto& Manager = FAngelscriptManager::Get();
        const asUINT ParamCount = Method->GetParamCount();
        Result.Reserve(ParamCount);

        for (asUINT Index = 0; Index < ParamCount; ++Index)
        {
            int     ParamTypeId = 0;
            asDWORD Flags       = asTM_NONE;
            Method->GetParam(Index, &ParamTypeId, &Flags);

            auto Param = FForEachParam{};
            Param._IsConst = (Flags & asTM_CONST)    != 0;
            Param._IsRef   = (Flags & asTM_INOUTREF) != 0;   // any of in/out/inout
            if (auto* AsStruct = Manager.GetUnrealStructFromAngelscriptTypeId(ParamTypeId))
            { Param._Struct = Cast<UScriptStruct>(AsStruct); }

            Result.Add(Param);
        }
#endif

        return Result;
    }

    // ----------------------------------------------------------------------------------------------------------------
    // Build + validate the signature. Grammar: void ForEachEntity(FCk_Time, [FCk_Handle,] <fragment params>...).
    // OutHasForEachEntity is false when the class has no ForEachEntity at all (caller skips it, no driver emitted).

    auto
    Build_Signature(
        UClass* InClass,
        bool& OutHasForEachEntity)
        -> FSignature
    {
        OutHasForEachEntity = false;
        auto Signature = FSignature{};

        const auto Params = Reflect_ForEachEntityParams(InClass);
        if (Params.IsEmpty())
        { return Signature; }

        OutHasForEachEntity = true;

        const auto* TimeStruct   = FCk_Time::StaticStruct();
        const auto* HandleStruct = FCk_Handle::StaticStruct();

        if (Params[0]._Struct != TimeStruct)
        {
            Signature._Error = TEXT("first parameter must be FCk_Time");
            return Signature;
        }

        auto FragmentStart = 1;
        if (Params.Num() > 1 && Params[1]._Struct == HandleStruct)
        {
            Signature._HasHandleParam = true;
            FragmentStart = 2;
        }

        for (auto Index = FragmentStart; Index < Params.Num(); ++Index)
        {
            const auto& Param = Params[Index];

            if (ck::Is_NOT_Valid(Param._Struct))
            {
                Signature._Error = ck::Format_UE(TEXT("parameter [{}] does not resolve to a known USTRUCT fragment"), Index);
                return Signature;
            }
            if (Param._Struct == TimeStruct || Param._Struct == HandleStruct)
            {
                Signature._Error = ck::Format_UE(
                    TEXT("FCk_Time / FCk_Handle may only appear as the leading parameters (parameter [{}])"), Index);
                return Signature;
            }

            const auto IsDuplicate = Signature._FragmentParams.ContainsByPredicate(
                [&](const FForEachParam& InExisting) { return InExisting._Struct == Param._Struct; });
            if (IsDuplicate)
            {
                Signature._Error = ck::Format_UE(TEXT("fragment [{}] appears more than once"), Param._Struct->GetName());
                return Signature;
            }

            Signature._FragmentParams.Add(Param);
        }

        return Signature;
    }

    // ----------------------------------------------------------------------------------------------------------------

    auto
    Overrides_ForEachBatch(
        UClass* InClass)
        -> bool
    {
        const auto* Fn = InClass->FindFunctionByName(FName{TEXT("ForEachBatch")});
        return Fn != nullptr && Fn->GetOuterUClass() != UCk_Processor_Script_Base_UE::StaticClass();
    }

    auto
    Get_SourceName(
        UStruct* InType)
        -> FString
    {
        return InType->GetPrefixCPP() + InType->GetName();
    }

    // ----------------------------------------------------------------------------------------------------------------
    // Emit one driver class (pure text — no reflection). An invalid signature emits a compile-visible error instead.

    auto
    Emit_DriverBlock(
        UClass* InDevClass,
        const FSignature& InSignature)
        -> FString
    {
        const auto DevName = Get_SourceName(InDevClass);

        if (NOT InSignature._Error.IsEmpty())
        {
            auto Error = FString{};
            Error += FString::Printf(TEXT("// !!! SIGNATURE ERROR in %s — %s !!!\n"), *DevName, *InSignature._Error);
            Error += TEXT("// Fix the ForEachEntity signature; the next line fails compilation on purpose.\n");
            Error += FString::Printf(TEXT("SIGNATURE_ERROR_%s;\n\n"), *InDevClass->GetName());
            return Error;
        }

        const auto DriverName = DevName + GDriverSuffix;

        auto Out = FString{};
        Out += FString::Printf(TEXT("class %s : UCk_Processor_Script_Base_UE\n"), *DriverName);
        Out += TEXT("{\n");
        Out += TEXT("    UFUNCTION(BlueprintOverride)\n");
        Out += TEXT("    void Configure(FCk_ScriptProcessorQuery& Query)\n");
        Out += TEXT("    {\n");
        for (const auto& Param : InSignature._FragmentParams)
        {
            const auto  FragName = Get_SourceName(Param._Struct);
            const auto* Access   = (Param._IsRef && NOT Param._IsConst) ? TEXT("ReadWrite") : TEXT("ReadOnly");
            Out += FString::Printf(TEXT("        Query.%s(%s);\n"), Access, *FragName);
        }
        Out += FString::Printf(TEXT("        auto Dev = Cast<%s>(_IterationTarget);\n"), *DevName);
        Out += TEXT("        if (Dev != nullptr) { Dev.Configure(Query); }\n");
        Out += TEXT("    }\n");
        Out += TEXT("\n");
        Out += TEXT("    UFUNCTION(BlueprintOverride)\n");
        Out += TEXT("    void ForEachBatch(FCk_ScriptQueryBatch Batch, FCk_Time InDeltaT)\n");
        Out += TEXT("    {\n");
        Out += FString::Printf(TEXT("        auto Dev = Cast<%s>(_IterationTarget);\n"), *DevName);
        Out += TEXT("        if (Dev == nullptr) { return; }\n");
        Out += TEXT("        for (int32 i = 0; i < Batch.Num(); ++i)\n");
        Out += TEXT("        {\n");

        auto CallArgs = FString{TEXT("InDeltaT")};
        if (InSignature._HasHandleParam)
        { CallArgs += TEXT(", Batch.GetHandle(i)"); }

        for (auto Index = 0; Index < InSignature._FragmentParams.Num(); ++Index)
        {
            const auto& Param     = InSignature._FragmentParams[Index];
            const auto  FragName  = Get_SourceName(Param._Struct);
            const auto* Qualifier = Param._IsConst ? TEXT("const ") : TEXT("");
            Out += FString::Printf(TEXT("            %s%s& P%d = Batch.Get(i, %s);\n"), Qualifier, *FragName, Index, *FragName);
            CallArgs += FString::Printf(TEXT(", P%d"), Index);
        }

        Out += FString::Printf(TEXT("            Dev.ForEachEntity(%s);\n"), *CallArgs);
        Out += TEXT("        }\n");
        Out += TEXT("    }\n");
        Out += TEXT("}\n\n");
        return Out;
    }

    // ----------------------------------------------------------------------------------------------------------------
    // Candidate filter — the same staleness/placeholder chain the AutoTest generator uses.

    auto
    Is_IncludedDriverClass(
        UClass* InClass,
        UClass* InBase)
        -> bool
    {
        if (ck::Is_NOT_Valid(InClass, ck::IsValid_Policy_NullptrOnly{}))                     { return false; }
        if (InClass == InBase)                                                               { return false; }
        if (NOT InClass->IsChildOf(InBase))                                                  { return false; }
        if (InClass->HasAnyClassFlags(CLASS_Abstract | CLASS_Deprecated | CLASS_NewerVersionExists)) { return false; }
        if (InClass->IsUnreachable() || InClass->HasAnyFlags(RF_BeginDestroyed | RF_FinishDestroyed)) { return false; }

#if WITH_ANGELSCRIPT_CK
        if (auto* ASClass = UASClass::GetFirstASClass(InClass))
        {
            if (ASClass->NewerVersion != nullptr) { return false; }
            const auto SourcePath = ASClass->GetSourceFilePath();
            if (NOT SourcePath.IsEmpty() && NOT FPaths::FileExists(SourcePath)) { return false; }
        }
#endif

        if (UCk_Utils_Reflection_UE::Is_PlaceholderClass(InClass)) { return false; }
        return true;
    }

    // A hand-authored <X>_Driver (source not under /Script/Generated/) suppresses generation for that dev class.

    auto
    Has_HandAuthoredDriver(
        const FString& InDriverBareName)
        -> bool
    {
        auto* Existing = FindFirstObject<UClass>(*InDriverBareName, EFindFirstObjectOptions::None);
        if (ck::Is_NOT_Valid(Existing, ck::IsValid_Policy_NullptrOnly{})) { return false; }

        if (Existing->IsUnreachable() || Existing->HasAnyFlags(RF_BeginDestroyed | RF_FinishDestroyed)) { return false; }
        if (Existing->HasAnyClassFlags(CLASS_NewerVersionExists | CLASS_Deprecated))                    { return false; }

#if WITH_ANGELSCRIPT_CK
        if (auto* ExistingAS = UASClass::GetFirstASClass(Existing))
        {
            if (ExistingAS->NewerVersion != nullptr) { return false; }

            const auto SourcePath = ExistingAS->GetSourceFilePath();
            if (NOT SourcePath.IsEmpty() && NOT FPaths::FileExists(SourcePath)) { return false; }
            if (SourcePath.IsEmpty()) { return true; }

            auto Normalized = FPaths::ConvertRelativePathToFull(SourcePath);
            FPaths::NormalizeFilename(Normalized);
            return NOT Normalized.Contains(GGeneratedDirSegment, ESearchCase::IgnoreCase);
        }
#endif

        return true;   // C++ class with the name -> hand-authored
    }

    // ----------------------------------------------------------------------------------------------------------------
    // Per-plugin bucketing (mirrors the AutoTest generator).

    struct FPluginBucket
    {
        FString         _PluginName;
        FString         _OutputFilePath;
        TArray<UClass*> _Classes;
    };

    auto
    Find_PluginByPathPrefix(
        const FString& InSourcePath)
        -> TSharedPtr<IPlugin>
    {
        auto FullPath = FPaths::ConvertRelativePathToFull(InSourcePath);
        FPaths::NormalizeFilename(FullPath);

        auto Best    = TSharedPtr<IPlugin>{};
        auto BestLen = 0;
        for (const auto& Plugin : IPluginManager::Get().GetEnabledPlugins())
        {
            auto BaseDir = FPaths::ConvertRelativePathToFull(Plugin->GetBaseDir());
            FPaths::NormalizeDirectoryName(BaseDir);
            if (FullPath.StartsWith(BaseDir) && BaseDir.Len() > BestLen)
            {
                Best    = Plugin;
                BestLen = BaseDir.Len();
            }
        }
        return Best;
    }

    auto
    Find_PluginForClass(
        UClass* InClass,
        const TMap<FString, TSharedRef<IPlugin>>& InModuleToPlugin)
        -> TSharedPtr<IPlugin>
    {
        const auto PackageName = InClass->GetOutermost()->GetName();   // "/Script/<Module>" or "/Script/Angelscript"
        static const auto ScriptPrefix = FString{TEXT("/Script/")};
        if (PackageName.StartsWith(ScriptPrefix))
        {
            const auto ModuleName = PackageName.RightChop(ScriptPrefix.Len());
            if (const auto* Found = InModuleToPlugin.Find(ModuleName))
            { return *Found; }
        }

#if WITH_ANGELSCRIPT_CK
        if (auto* ASClass = UASClass::GetFirstASClass(InClass))
        {
            const auto SourcePath = ASClass->GetSourceFilePath();
            if (NOT SourcePath.IsEmpty())
            { return Find_PluginByPathPrefix(SourcePath); }
        }
#endif

        return nullptr;
    }

    auto
    Build_ModuleToPluginMap()
        -> TMap<FString, TSharedRef<IPlugin>>
    {
        auto Map = TMap<FString, TSharedRef<IPlugin>>{};
        for (const auto& Plugin : IPluginManager::Get().GetEnabledPlugins())
        {
            for (const auto& Module : Plugin->GetDescriptor().Modules)
            {
                Map.Add(Module.Name.ToString(), Plugin);
            }
        }
        return Map;
    }

    auto
    Bucket_ClassesByPlugin(
        const TArray<UClass*>& InClasses)
        -> TArray<FPluginBucket>
    {
        const auto ModuleToPlugin = Build_ModuleToPluginMap();
        auto BucketMap = TMap<FString, FPluginBucket>{};

        for (auto* Class : InClasses)
        {
            auto PluginName = FString{};
            auto OutputDir  = FString{};

            if (const auto Plugin = Find_PluginForClass(Class, ModuleToPlugin))
            {
                PluginName = Plugin->GetName();
                OutputDir  = Plugin->GetBaseDir() / TEXT("Script") / TEXT("Generated");
            }
            else
            {
                PluginName = FApp::GetProjectName();
                OutputDir  = FPaths::ProjectDir() / TEXT("Script") / TEXT("Generated");
            }

            if (NOT BucketMap.Contains(PluginName))
            {
                auto Bucket = FPluginBucket{};
                Bucket._PluginName     = PluginName;
                Bucket._OutputFilePath = OutputDir / (PluginName + TEXT("_ScriptProcessorDrivers.as"));
                BucketMap.Add(PluginName, MoveTemp(Bucket));
            }
            BucketMap[PluginName]._Classes.Add(Class);
        }

        auto Result = TArray<FPluginBucket>{};
        BucketMap.GenerateValueArray(Result);
        Result.Sort([](const FPluginBucket& A, const FPluginBucket& B) { return A._PluginName < B._PluginName; });
        return Result;
    }

    // ----------------------------------------------------------------------------------------------------------------

    auto
    Write_BucketIfChanged(
        const FPluginBucket& InBucket,
        const FString& InContent)
        -> void
    {
        const auto OutputDir = FPaths::GetPath(InBucket._OutputFilePath);
        IFileManager::Get().MakeDirectory(*OutputDir, /*Tree=*/true);

        auto ExistingContent = FString{};
        const auto HasExisting = FFileHelper::LoadFileToString(ExistingContent, *InBucket._OutputFilePath);

        auto ContentForCompare  = InContent;       ContentForCompare.ReplaceInline(TEXT("\r\n"), TEXT("\n"));
        auto ExistingForCompare = ExistingContent; ExistingForCompare.ReplaceInline(TEXT("\r\n"), TEXT("\n"));

        if (HasExisting && ExistingForCompare.Equals(ContentForCompare, ESearchCase::CaseSensitive))
        { return; }   // up-to-date — writing would re-trigger the post-compile pass (infinite loop)

        auto ToWrite = InContent;
#if PLATFORM_WINDOWS
        ToWrite.ReplaceInline(TEXT("\r\n"), TEXT("\n"));
        ToWrite.ReplaceInline(TEXT("\n"), TEXT("\r\n"));
#endif

        const auto Wrote = FFileHelper::SaveStringToFile(ToWrite, *InBucket._OutputFilePath,
            FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);

        if (Wrote)
        { ck::angelscriptgenerator::Log(TEXT("[CkAS ScriptProcDrivers] [{}] -> {}"), InBucket._PluginName, InBucket._OutputFilePath); }
        else
        { ck::angelscriptgenerator::Error(TEXT("[CkAS ScriptProcDrivers] write failed [{}]"), InBucket._OutputFilePath); }
    }
}

#endif // WITH_EDITOR

// --------------------------------------------------------------------------------------------------------------------

auto
    FCkScriptProcessorDriverGenerator::
    GenerateAll()
    -> void
{
#if WITH_EDITOR
    using namespace ck::scriptprocessor_driver_generator;

    // Single-writer gate — a secondary editor does not regenerate.
    if (NOT FCkAngelscriptGenerator_RegenOwnership::Try_AcquireOrGet_IsOwner(TEXT("ScriptProcessorDriverGenerator.GenerateAll")))
    { return; }

    // The base is a C++ class, so StaticClass() is always available (no name lookup like the AutoTest generator's
    // AS-defined base needs).
    auto* BaseClass = UCk_Processor_Script_Base_UE::StaticClass();

    auto Candidates = TArray<UClass*>{};
    for (TObjectIterator<UClass> ClassIterator; ClassIterator; ++ClassIterator)
    {
        if (Is_IncludedDriverClass(*ClassIterator, BaseClass))
        { Candidates.Add(*ClassIterator); }
    }
    Candidates.Sort([](const UClass& A, const UClass& B) { return A.GetPathName() < B.GetPathName(); });

    auto CandidateNames = TSet<FString>{};
    for (const auto* Class : Candidates)
    { CandidateNames.Add(Class->GetName()); }

    auto EmitClasses = TArray<UClass*>{};
    auto SignatureByClass = TMap<UClass*, FSignature>{};

    for (auto* Class : Candidates)
    {
        // The drivers themselves are subclasses too — never generate a driver for a driver. Mirrors the host's
        // routing guard: only a class whose dev sibling exists is a driver; an ordinary typed processor whose
        // name merely ends in _Driver still gets a driver generated (named <Name>_Driver_Driver).
        if (Class->GetName().EndsWith(GDriverSuffix) &&
            CandidateNames.Contains(Class->GetName().LeftChop(GDriverSuffix.Len())))
        { continue; }

        auto HasForEachEntity = false;
        auto Signature = Build_Signature(Class, HasForEachEntity);
        if (NOT HasForEachEntity)
        { continue; }   // legacy Tick processor or a direct ForEachBatch class — not our concern

        if (Signature._Error.IsEmpty() && Overrides_ForEachBatch(Class))
        { Signature._Error = TEXT("class declares both a ForEachEntity method and a ForEachBatch override — pick one"); }

        // Respect a hand-authored driver (e.g. an end-to-end test's driver before it is deleted in favour of codegen).
        // OBJECT name, not Get_SourceName: FindFirstObject matches UClass names, which never carry the U prefix.
        if (Has_HandAuthoredDriver(Class->GetName() + GDriverSuffix))
        { continue; }

        EmitClasses.Add(Class);
        SignatureByClass.Add(Class, MoveTemp(Signature));
    }

    const auto Buckets = Bucket_ClassesByPlugin(EmitClasses);

    for (const auto& Bucket : Buckets)
    {
        auto Content = FString{GFileHeader};
        for (auto* Class : Bucket._Classes)
        {
            if (const auto* Signature = SignatureByClass.Find(Class))
            { Content += Emit_DriverBlock(Class, *Signature); }
        }

        Write_BucketIfChanged(Bucket, Content);
    }
#endif // WITH_EDITOR
}
