#include "CkScriptProcessorDriverGenerator.h"

#include "CkAngelscriptGenerator/CkAngelscriptGenerator_Log.h"
#include "CkAngelscriptGenerator/CkAngelscriptGenerator_RegenOwnership.h"

#include "CkCore/Format/CkFormat.h"
#include "CkCore/Reflection/CkReflection_Utils.h"
#include "CkCore/Time/CkTime.h"
#include "CkCore/Validation/CkIsValid.h"

#include "CkEcs/Handle/CkHandle.h"
#include "CkEcs/Processor/CkProcessor_Script.h"

#include <HAL/FileManager.h>
#include <Interfaces/IPluginManager.h>
#include <Misc/App.h>
#include <Misc/FileHelper.h>
#include <Misc/Paths.h>
#include <UObject/Class.h>
#include <UObject/UObjectIterator.h>

#if WITH_ANGELSCRIPT_CK
#include "ClassGenerator/ASClass.h"   // UASClass + FAngelscriptManager + angelscript.h (asITypeInfo/asIScriptFunction/asTM_*)
#endif

// --------------------------------------------------------------------------------------------------------------------

#if WITH_EDITOR

namespace ck::scriptprocessor_driver_generator
{
    static const TCHAR* GFileHeader =
        TEXT("// GENERATED by CkScriptProcessorDriverGenerator - DO NOT EDIT. Regenerated on AS compile.\n")
        TEXT("// One <Dev>_Driver per typed script processor - a SUBCLASS of the dev class whose ForEachBatch loops the\n")
        TEXT("// native join and calls the inherited ForEachEntity. Signature discovery is via AS-VM reflection.\n")
        TEXT("\n");

    static const auto GDriverSuffix = FString{TEXT("_Driver")};
    static const auto GGeneratedDirSegment = FString{TEXT("/Script/Generated/")};

    // Editor-only script root. The Angelscript fork skips this whole directory when bUseEditorScripts is false,
    // which is how every non-editor boot runs -- Gauntlet among them (Config/DefaultGame.ini: "AngelScript
    // classes (under Script/Dev/, skipped when bUseEditorScripts=false)").
    static const auto GEditorOnlyScriptDirSegment = FString{TEXT("/Script/Dev/")};

    // ----------------------------------------------------------------------------------------------------------------

    struct FForEachParam
    {
        UScriptStruct* _Struct  = nullptr;
        bool           _IsConst = false;   // const& -> ReadOnly
        bool           _IsRef   = false;   // reference (any direction); false => by-value
    };

    struct FSignature
    {
        bool                  _HasHandleParam = false;
        TArray<FForEachParam> _FragmentParams;
        FString               _Error;   // non-empty => invalid signature; text names the violation
    };

    // ----------------------------------------------------------------------------------------------------------------
    // Empty result means "not a typed processor" — not an AS class, or no ForEachEntity at all.

    auto
    Reflect_ForEachEntityParams(
        UClass* InClass)
        -> TArray<FForEachParam>
    {
        auto Result = TArray<FForEachParam>{};

#if WITH_ANGELSCRIPT_CK
        auto* ASClass = Cast<UASClass>(InClass);
        if (ASClass == nullptr || ASClass->ScriptTypePtr == nullptr)
        { return Result; }

        auto* ScriptType = static_cast<asITypeInfo*>(ASClass->ScriptTypePtr);
        if (ScriptType == nullptr)
        { return Result; }

        static const char* const MethodName = "ForEachEntity";

        auto* Method = ScriptType->GetMethodByName(MethodName);
        if (Method == nullptr)
        {
            // GetMethodByName returns null for an overloaded name — disambiguate by scanning.
            for (asUINT Index = 0, Count = ScriptType->GetMethodCount(); Index < Count; ++Index)
            {
                auto* Candidate = ScriptType->GetMethodByIndex(Index);
                if (Candidate != nullptr && FCStringAnsi::Strcmp(Candidate->GetName(), MethodName) == 0)
                {
                    Method = Candidate;
                    break;
                }
            }
        }
        if (Method == nullptr)
        { return Result; }

        auto& Manager = FAngelscriptManager::Get();
        const asUINT ParamCount = Method->GetParamCount();
        Result.Reserve(ParamCount);

        for (asUINT Index = 0; Index < ParamCount; ++Index)
        {
            int     ParamTypeId = 0;
            asDWORD Flags       = asTM_NONE;
            Method->GetParam(Index, &ParamTypeId, &Flags);

            auto Param = FForEachParam{};
            Param._IsConst = (Flags & asTM_CONST)    != 0;
            Param._IsRef   = (Flags & asTM_INOUTREF) != 0;   // any of in/out/inout
            if (auto* AsStruct = Manager.GetUnrealStructFromAngelscriptTypeId(ParamTypeId))
            { Param._Struct = Cast<UScriptStruct>(AsStruct); }

            Result.Add(Param);
        }
#endif

        return Result;
    }

    // ----------------------------------------------------------------------------------------------------------------
    // Grammar: void ForEachEntity(FCk_Time, [FCk_Handle,] <fragment params>...). OutHasForEachEntity
    // false => the class has none at all, and the caller emits no driver rather than an error.

    auto
    Build_Signature(
        UClass* InClass,
        bool& OutHasForEachEntity)
        -> FSignature
    {
        OutHasForEachEntity = false;
        auto Signature = FSignature{};

        const auto Params = Reflect_ForEachEntityParams(InClass);
        if (Params.IsEmpty())
        { return Signature; }

        OutHasForEachEntity = true;

        const auto* TimeStruct   = FCk_Time::StaticStruct();
        const auto* HandleStruct = FCk_Handle::StaticStruct();

        if (Params[0]._Struct != TimeStruct)
        {
            Signature._Error = TEXT("first parameter must be FCk_Time");
            return Signature;
        }

        auto FragmentStart = 1;
        if (Params.Num() > 1 && Params[1]._Struct == HandleStruct)
        {
            Signature._HasHandleParam = true;
            FragmentStart = 2;
        }

        for (auto Index = FragmentStart; Index < Params.Num(); ++Index)
        {
            const auto& Param = Params[Index];

            if (ck::Is_NOT_Valid(Param._Struct))
            {
                Signature._Error = ck::Format_UE(TEXT("parameter [{}] does not resolve to a known USTRUCT fragment"), Index);
                return Signature;
            }
            if (Param._Struct == TimeStruct || Param._Struct == HandleStruct)
            {
                Signature._Error = ck::Format_UE(
                    TEXT("FCk_Time / FCk_Handle may only appear as the leading parameters (parameter [{}])"), Index);
                return Signature;
            }

            const auto IsDuplicate = Signature._FragmentParams.ContainsByPredicate(
                [&](const FForEachParam& InExisting) { return InExisting._Struct == Param._Struct; });
            if (IsDuplicate)
            {
                Signature._Error = ck::Format_UE(TEXT("fragment [{}] appears more than once"), Param._Struct->GetName());
                return Signature;
            }

            Signature._FragmentParams.Add(Param);
        }

        return Signature;
    }

    // ----------------------------------------------------------------------------------------------------------------

    auto
    Overrides_ForEachBatch(
        UClass* InClass)
        -> bool
    {
        const auto* Fn = InClass->FindFunctionByName(FName{TEXT("ForEachBatch")});
        return Fn != nullptr && Fn->GetOuterUClass() != UCk_Processor_Script_Base_UE::StaticClass();
    }

    // Gates the emitted Super::Configure(Query) — emitting it unconditionally would Super-call the
    // bodiless C++ BlueprintImplementableEvent.
    auto
    Overrides_Configure(
        UClass* InClass)
        -> bool
    {
        const auto* Fn = InClass->FindFunctionByName(FName{TEXT("Configure")});
        return Fn != nullptr && Fn->GetOuterUClass() != UCk_Processor_Script_Base_UE::StaticClass();
    }

    auto
    Get_SourceName(
        UStruct* InType)
        -> FString
    {
        return InType->GetPrefixCPP() + InType->GetName();
    }

    // ----------------------------------------------------------------------------------------------------------------
    // An invalid signature deliberately emits AS that fails to compile, rather than nothing.

    auto
    Emit_DriverBlock(
        UClass* InDevClass,
        const FSignature& InSignature)
        -> FString
    {
        const auto DevName = Get_SourceName(InDevClass);

        if (NOT InSignature._Error.IsEmpty())
        {
            auto Error = FString{};
            Error += FString::Printf(TEXT("// !!! SIGNATURE ERROR in %s - %s !!!\n"), *DevName, *InSignature._Error);
            Error += TEXT("// Fix the ForEachEntity signature; the next line fails compilation on purpose.\n");
            Error += FString::Printf(TEXT("SIGNATURE_ERROR_%s;\n\n"), *InDevClass->GetName());
            return Error;
        }

        const auto DriverName = DevName + GDriverSuffix;

        // Subclassing gets ForEachEntity inherited and Super::Configure reaching the dev's own
        // override — no iteration-target indirection, no casts.
        auto Out = FString{};
        Out += FString::Printf(TEXT("class %s : %s\n"), *DriverName, *DevName);
        Out += TEXT("{\n");
        Out += TEXT("    UFUNCTION(BlueprintOverride)\n");
        Out += TEXT("    void Configure(FCk_ScriptProcessorQuery& Query)\n");
        Out += TEXT("    {\n");
        for (const auto& Param : InSignature._FragmentParams)
        {
            const auto  FragName = Get_SourceName(Param._Struct);
            const auto* Access   = (Param._IsRef && NOT Param._IsConst) ? TEXT("ReadWrite") : TEXT("ReadOnly");
            Out += FString::Printf(TEXT("        Query.%s(%s);\n"), Access, *FragName);
        }
        if (Overrides_Configure(InDevClass))
        { Out += TEXT("        Super::Configure(Query);\n"); }
        Out += TEXT("    }\n");
        Out += TEXT("\n");
        Out += TEXT("    UFUNCTION(BlueprintOverride)\n");
        Out += TEXT("    void ForEachBatch(FCk_ScriptQueryBatch Batch, FCk_Time InDeltaT)\n");
        Out += TEXT("    {\n");
        // Batch level, not per-entity: authored ForEachEntity bodies stay free of stat boilerplate.
        Out += TEXT("        auto _CkPerfScope = ck::ScopedStat();\n");
        // Hoisted: every Batch accessor resolves the live batch state under a global lock
        // (CkDynamic_ScriptQueryBatch.cpp), so Num() in the for-condition paid one lock per
        // entity per processor per frame. The count cannot change mid-batch by contract.
        Out += TEXT("        const int32 NumEntities = Batch.Num();\n");
        Out += TEXT("        for (int32 i = 0; i < NumEntities; ++i)\n");
        Out += TEXT("        {\n");

        auto CallArgs = FString{TEXT("InDeltaT")};
        if (InSignature._HasHandleParam)
        {
            // GetHandle() returns a temporary, which cannot bind to ForEachEntity's FCk_Handle&.
            Out += TEXT("            auto Handle = Batch.GetHandle(i);\n");
            CallArgs += TEXT(", Handle");
        }

        for (auto Index = 0; Index < InSignature._FragmentParams.Num(); ++Index)
        {
            const auto& Param     = InSignature._FragmentParams[Index];
            const auto  FragName  = Get_SourceName(Param._Struct);
            const auto* Qualifier = Param._IsConst ? TEXT("const ") : TEXT("");
            const auto* Accessor  = Param._IsConst ? TEXT("GetReadOnly") : TEXT("Get");
            Out += FString::Printf(TEXT("            %s%s& P%d = Batch.%s(i, %s);\n"),
                Qualifier, *FragName, Index, Accessor, *FragName);
            CallArgs += FString::Printf(TEXT(", P%d"), Index);
        }

        Out += FString::Printf(TEXT("            ForEachEntity(%s);\n"), *CallArgs);
        Out += TEXT("        }\n");
        Out += TEXT("    }\n");
        Out += TEXT("}\n\n");
        return Out;
    }

    // A dev class under an EDITOR-ONLY script root gets no generated driver, and that is a correctness rule
    // rather than a tidiness one. The generated file is compiled in EVERY configuration; the dev class it
    // subclasses is not. Emit the pair anyway and a non-editor boot meets a driver whose super does not exist --
    // which is not a localised failure, because `unknown super type` aborts Angelscript preprocessing outright,
    // so NOTHING compiles and every test in that configuration dies at once.
    //
    // One dev-only processor did exactly that to the entire Gauntlet layer, and the editor-side gate could not
    // see it: `--test` boots WITH editor scripts, the super resolves, and the suite stays green while the other
    // configuration is dark. A generator emitting into an always-compiled file has to answer for the
    // configurations it cannot observe.
    auto
    Is_EditorOnlyScriptClass(
        UClass* InClass)
        -> bool
    {
#if WITH_ANGELSCRIPT_CK
        auto* AsClass = UASClass::GetFirstASClass(InClass);
        if (AsClass == nullptr)
        { return false; }

        const auto SourcePath = AsClass->GetSourceFilePath();
        if (SourcePath.IsEmpty())
        { return false; }

        auto Normalized = FPaths::ConvertRelativePathToFull(SourcePath);
        FPaths::NormalizeFilename(Normalized);
        return Normalized.Contains(GEditorOnlyScriptDirSegment, ESearchCase::IgnoreCase);
#else
        return false;
#endif
    }

    // ----------------------------------------------------------------------------------------------------------------
    // Candidate filter — the same staleness/placeholder chain the AutoTest generator uses.

    auto
    Is_IncludedDriverClass(
        UClass* InClass,
        UClass* InBase)
        -> bool
    {
        if (ck::Is_NOT_Valid(InClass))
        { return false; }
        if (InClass == InBase)
        { return false; }
        if (NOT InClass->IsChildOf(InBase))
        { return false; }
        if (InClass->HasAnyClassFlags(CLASS_Abstract | CLASS_Deprecated | CLASS_NewerVersionExists))
        { return false; }
        if (InClass->IsUnreachable() || InClass->HasAnyFlags(RF_BeginDestroyed | RF_FinishDestroyed))
        { return false; }

#if WITH_ANGELSCRIPT_CK
        if (auto* ASClass = UASClass::GetFirstASClass(InClass))
        {
            if (ASClass->NewerVersion != nullptr)
            { return false; }
            const auto SourcePath = ASClass->GetSourceFilePath();
            if (NOT SourcePath.IsEmpty() && NOT FPaths::FileExists(SourcePath))
            { return false; }
        }
#endif

        if (UCk_Utils_Reflection_UE::Is_PlaceholderClass(InClass))
        { return false; }
        return true;
    }

    // A hand-authored <X>_Driver (source not under /Script/Generated/) suppresses generation for that dev class.

    auto
    Has_HandAuthoredDriver(
        const FString& InDriverBareName)
        -> bool
    {
        auto* Existing = FindFirstObject<UClass>(*InDriverBareName, EFindFirstObjectOptions::None);
        if (ck::Is_NOT_Valid(Existing))
        { return false; }

        if (Existing->IsUnreachable() || Existing->HasAnyFlags(RF_BeginDestroyed | RF_FinishDestroyed))
        { return false; }
        if (Existing->HasAnyClassFlags(CLASS_NewerVersionExists | CLASS_Deprecated))
        { return false; }

#if WITH_ANGELSCRIPT_CK
        if (auto* ExistingAS = UASClass::GetFirstASClass(Existing))
        {
            if (ExistingAS->NewerVersion != nullptr)
            { return false; }

            const auto SourcePath = ExistingAS->GetSourceFilePath();
            if (NOT SourcePath.IsEmpty() && NOT FPaths::FileExists(SourcePath))
            { return false; }
            if (SourcePath.IsEmpty())
            { return true; }

            auto Normalized = FPaths::ConvertRelativePathToFull(SourcePath);
            FPaths::NormalizeFilename(Normalized);
            return NOT Normalized.Contains(GGeneratedDirSegment, ESearchCase::IgnoreCase);
        }
#endif

        return true;   // C++ class with the name -> hand-authored
    }

    // ----------------------------------------------------------------------------------------------------------------

    struct FPluginBucket
    {
        FString         _PluginName;
        FString         _OutputFilePath;
        TArray<UClass*> _Classes;
    };

    auto
    Find_PluginByPathPrefix(
        const FString& InSourcePath)
        -> TSharedPtr<IPlugin>
    {
        auto FullPath = FPaths::ConvertRelativePathToFull(InSourcePath);
        FPaths::NormalizeFilename(FullPath);

        auto Best    = TSharedPtr<IPlugin>{};
        auto BestLen = 0;
        for (const auto& Plugin : IPluginManager::Get().GetEnabledPlugins())
        {
            auto BaseDir = FPaths::ConvertRelativePathToFull(Plugin->GetBaseDir());
            FPaths::NormalizeDirectoryName(BaseDir);
            if (FullPath.StartsWith(BaseDir) && BaseDir.Len() > BestLen)
            {
                Best    = Plugin;
                BestLen = BaseDir.Len();
            }
        }
        return Best;
    }

    auto
    Find_PluginForClass(
        UClass* InClass,
        const TMap<FString, TSharedRef<IPlugin>>& InModuleToPlugin)
        -> TSharedPtr<IPlugin>
    {
        const auto PackageName = InClass->GetOutermost()->GetName();   // "/Script/<Module>" or "/Script/Angelscript"
        static const auto ScriptPrefix = FString{TEXT("/Script/")};
        if (PackageName.StartsWith(ScriptPrefix))
        {
            const auto ModuleName = PackageName.RightChop(ScriptPrefix.Len());
            if (const auto* Found = InModuleToPlugin.Find(ModuleName))
            { return *Found; }
        }

#if WITH_ANGELSCRIPT_CK
        if (auto* ASClass = UASClass::GetFirstASClass(InClass))
        {
            const auto SourcePath = ASClass->GetSourceFilePath();
            if (NOT SourcePath.IsEmpty())
            { return Find_PluginByPathPrefix(SourcePath); }
        }
#endif

        return nullptr;
    }

    auto
    Build_ModuleToPluginMap()
        -> TMap<FString, TSharedRef<IPlugin>>
    {
        auto Map = TMap<FString, TSharedRef<IPlugin>>{};
        for (const auto& Plugin : IPluginManager::Get().GetEnabledPlugins())
        {
            for (const auto& Module : Plugin->GetDescriptor().Modules)
            {
                Map.Add(Module.Name.ToString(), Plugin);
            }
        }
        return Map;
    }

    auto
    Bucket_ClassesByPlugin(
        const TArray<UClass*>& InClasses)
        -> TArray<FPluginBucket>
    {
        const auto ModuleToPlugin = Build_ModuleToPluginMap();
        auto BucketMap = TMap<FString, FPluginBucket>{};

        for (auto* Class : InClasses)
        {
            auto PluginName = FString{};
            auto ScriptRoot = FString{};

            if (const auto Plugin = Find_PluginForClass(Class, ModuleToPlugin))
            {
                PluginName = Plugin->GetName();
                ScriptRoot = Plugin->GetBaseDir() / TEXT("Script");
            }
            else
            {
                PluginName = FApp::GetProjectName();
                ScriptRoot = FPaths::ProjectDir() / TEXT("Script");
            }

            // A driver has to live wherever its SUPER lives, because the two are compiled or skipped together.
            // An editor-only dev class is absent from every non-editor boot, so its driver goes under the same
            // editor-only root and disappears with it; emitting it beside the shipping drivers instead is what
            // leaves a subclass of a class that does not exist, and `unknown super type` does not fail just that
            // driver -- it aborts Angelscript preprocessing, so the whole configuration compiles nothing.
            //
            // Skipping generation instead would be worse than the bug: the driver IS the dispatch (its ForEachBatch
            // is what ever calls ForEachEntity), so a dev processor without one silently stops running in the
            // editor too, taking whatever depends on it -- Bb.Snapshot.DemoPlaqueRestore, for one -- down with it.
            const auto IsEditorOnly = Is_EditorOnlyScriptClass(Class);
            const auto OutputDir    = IsEditorOnly
                ? ScriptRoot / TEXT("Dev") / TEXT("Generated")
                : ScriptRoot / TEXT("Generated");

            // Keyed apart so the two never share a bucket; the FILE name stays the plugin's, since the directory
            // is what distinguishes them.
            const auto BucketKey = IsEditorOnly ? PluginName + TEXT("[EditorOnly]") : PluginName;

            if (NOT BucketMap.Contains(BucketKey))
            {
                auto Bucket = FPluginBucket{};
                Bucket._PluginName     = PluginName;
                Bucket._OutputFilePath = OutputDir / (PluginName + TEXT("_ScriptProcessorDrivers.as"));
                BucketMap.Add(BucketKey, MoveTemp(Bucket));
            }
            BucketMap[BucketKey]._Classes.Add(Class);
        }

        auto Result = TArray<FPluginBucket>{};
        BucketMap.GenerateValueArray(Result);
        // By PATH, not name: a plugin can now own two buckets (shipping + editor-only) that share _PluginName.
        Result.Sort([](const FPluginBucket& A, const FPluginBucket& B) { return A._OutputFilePath < B._OutputFilePath; });
        return Result;
    }

    // ----------------------------------------------------------------------------------------------------------------

    auto
    Write_BucketIfChanged(
        const FPluginBucket& InBucket,
        const FString& InContent)
        -> void
    {
        const auto OutputDir = FPaths::GetPath(InBucket._OutputFilePath);
        IFileManager::Get().MakeDirectory(*OutputDir, /*Tree=*/true);

        auto ExistingContent = FString{};
        const auto HasExisting = FFileHelper::LoadFileToString(ExistingContent, *InBucket._OutputFilePath);

        auto ContentForCompare  = InContent;       ContentForCompare.ReplaceInline(TEXT("\r\n"), TEXT("\n"));
        auto ExistingForCompare = ExistingContent; ExistingForCompare.ReplaceInline(TEXT("\r\n"), TEXT("\n"));

        if (HasExisting && ExistingForCompare.Equals(ContentForCompare, ESearchCase::CaseSensitive))
        { return; }   // up-to-date — writing would re-trigger the post-compile pass (infinite loop)

        auto ToWrite = InContent;
#if PLATFORM_WINDOWS
        ToWrite.ReplaceInline(TEXT("\r\n"), TEXT("\n"));
        ToWrite.ReplaceInline(TEXT("\n"), TEXT("\r\n"));
#endif

        const auto Wrote = FFileHelper::SaveStringToFile(ToWrite, *InBucket._OutputFilePath,
            FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);

        if (Wrote)
        { ck::angelscriptgenerator::Log(TEXT("[CkAS ScriptProcDrivers] [{}] -> {}"), InBucket._PluginName, InBucket._OutputFilePath); }
        else
        { ck::angelscriptgenerator::Error(TEXT("[CkAS ScriptProcDrivers] write failed [{}]"), InBucket._OutputFilePath); }
    }
}

#endif // WITH_EDITOR

// --------------------------------------------------------------------------------------------------------------------

auto
    FCkScriptProcessorDriverGenerator::
    GenerateAll()
    -> void
{
#if WITH_EDITOR
    using namespace ck::scriptprocessor_driver_generator;

    if (NOT FCkAngelscriptGenerator_RegenOwnership::Try_AcquireOrGet_IsOwner(TEXT("ScriptProcessorDriverGenerator.GenerateAll")))
    { return; }

    auto* BaseClass = UCk_Processor_Script_Base_UE::StaticClass();

    auto Candidates = TArray<UClass*>{};
    for (TObjectIterator<UClass> ClassIterator; ClassIterator; ++ClassIterator)
    {
        if (Is_IncludedDriverClass(*ClassIterator, BaseClass))
        { Candidates.Add(*ClassIterator); }
    }
    Candidates.Sort([](const UClass& A, const UClass& B) { return A.GetPathName() < B.GetPathName(); });

    auto CandidateNames = TSet<FString>{};
    for (const auto* Class : Candidates)
    { CandidateNames.Add(Class->GetName()); }

    auto EmitClasses = TArray<UClass*>{};
    auto SignatureByClass = TMap<UClass*, FSignature>{};

    for (auto* Class : Candidates)
    {
        // Drivers are subclasses too — never emit a driver for a driver. Only a class whose dev
        // sibling EXISTS is one; a plain processor merely named *_Driver still gets its own.
        if (Class->GetName().EndsWith(GDriverSuffix) &&
            CandidateNames.Contains(Class->GetName().LeftChop(GDriverSuffix.Len())))
        { continue; }

        auto HasForEachEntity = false;
        auto Signature = Build_Signature(Class, HasForEachEntity);
        if (NOT HasForEachEntity)
        { continue; }   // legacy Tick processor or a direct ForEachBatch class — not our concern

        if (Signature._Error.IsEmpty() && Overrides_ForEachBatch(Class))
        { Signature._Error = TEXT("class declares both a ForEachEntity method and a ForEachBatch override - pick one"); }

        // OBJECT name, not Get_SourceName: FindFirstObject matches UClass names, which carry no U prefix.
        if (Has_HandAuthoredDriver(Class->GetName() + GDriverSuffix))
        { continue; }

        EmitClasses.Add(Class);
        SignatureByClass.Add(Class, MoveTemp(Signature));
    }

    const auto Buckets = Bucket_ClassesByPlugin(EmitClasses);

    for (const auto& Bucket : Buckets)
    {
        auto Content = FString{GFileHeader};
        for (auto* Class : Bucket._Classes)
        {
            if (const auto* Signature = SignatureByClass.Find(Class))
            { Content += Emit_DriverBlock(Class, *Signature); }
        }

        Write_BucketIfChanged(Bucket, Content);
    }
#endif // WITH_EDITOR
}
