# Generate-CkIcons.ps1
#
# Deterministic generator for the CkFoundation typed icon pipeline.
#
#   Input : Resources/Icons/CkIcons_Manifest.json   (semantic name -> MDI icon name)
#           Resources/Icons/Mdi/*.svg               (vendored, recoloured assets)
#           Resources/Icons/Mdi/mdi-names.txt       (pinned MDI name index — the typo oracle)
#   Output: Source/CkEditorTools/Public/CkEditorTools/Style/CkIcons_Generated.h
#           Source/CkEditorTools/Public/CkEditorTools/Style/CkIcons_Generated.cpp
#
# Every validation failure throws with a clear message (non-zero exit). A typo'd MDI name, a
# missing vendored SVG, or an unrecoloured SVG can NOT produce a silently missing icon.
#
# Usage:
#   pwsh ./Generate-CkIcons.ps1            # regenerate
#   pwsh ./Generate-CkIcons.ps1 -Check     # verify committed output matches the manifest (exit 3 on drift)

[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$PluginRoot   = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path
$ManifestPath = Join-Path $PluginRoot 'Resources/Icons/CkIcons_Manifest.json'
$MdiDir       = Join-Path $PluginRoot 'Resources/Icons/Mdi'
$NamesPath    = Join-Path $MdiDir 'mdi-names.txt'
$OutDir       = Join-Path $PluginRoot 'Source/CkEditorTools/Public/CkEditorTools/Style'
$OutHeader    = Join-Path $OutDir 'CkIcons_Generated.h'
$OutCpp       = Join-Path $OutDir 'CkIcons_Generated.cpp'

# ---------------------------------------------------------------------------------------------------------------------
# Load + validate
# ---------------------------------------------------------------------------------------------------------------------

if (-not (Test-Path $ManifestPath)) { throw "Manifest not found: $ManifestPath" }
if (-not (Test-Path $NamesPath))    { throw "Pinned MDI name index not found: $NamesPath" }

$Manifest = Get-Content $ManifestPath -Raw | ConvertFrom-Json
if ($Manifest._meta.format -ne 'ck-icon-manifest') { throw "Manifest _meta.format is '$($Manifest._meta.format)', expected 'ck-icon-manifest': $ManifestPath" }
if (-not $Manifest.icons -or $Manifest.icons.Count -eq 0) { throw "Manifest has no icons: $ManifestPath" }

$KnownMdiNames = [System.Collections.Generic.HashSet[string]]::new([string[]](Get-Content $NamesPath))
if ($KnownMdiNames.Count -lt 1000) { throw "MDI name index looks truncated ($($KnownMdiNames.Count) names): $NamesPath" }

$SeenSemantics = [System.Collections.Generic.HashSet[string]]::new()

foreach ($Entry in $Manifest.icons)
{
    if ([string]::IsNullOrWhiteSpace($Entry.semantic)) { throw "Manifest entry with empty 'semantic' (mdi='$($Entry.mdi)')" }
    if ([string]::IsNullOrWhiteSpace($Entry.mdi))      { throw "Manifest entry '$($Entry.semantic)' has empty 'mdi'" }

    if ($Entry.semantic -cnotmatch '^[A-Z][A-Za-z0-9]*$')
    { throw "Semantic name '$($Entry.semantic)' is not a valid PascalCase C++ identifier" }

    if (-not $SeenSemantics.Add($Entry.semantic))
    { throw "Duplicate semantic name in manifest: '$($Entry.semantic)'" }

    # The typo oracle: the pinned metadata is the authority on what MDI ships.
    if (-not $KnownMdiNames.Contains($Entry.mdi))
    { throw "Unknown MDI icon name '$($Entry.mdi)' (semantic '$($Entry.semantic)') — not present in the pinned $($Manifest._meta.mdiVersion) index ($NamesPath). Check spelling against https://pictogrammers.com/library/mdi/" }

    $SvgPath = Join-Path $MdiDir "$($Entry.mdi).svg"
    if (-not (Test-Path $SvgPath))
    { throw "Vendored SVG missing for '$($Entry.semantic)': $SvgPath — run Import-MdiIcon.ps1 -Name $($Entry.mdi)" }

    $Svg = Get-Content $SvgPath -Raw
    if ($Svg -notmatch 'fill="#FFFFFF"')
    { throw "SVG is not recoloured (no fill=`"#FFFFFF`" on its paths) and would rasterize as an untintable black glyph: $SvgPath" }

    foreach ($Forbidden in @('<style', '<text', '<filter', 'class='))
    {
        if ($Svg.Contains($Forbidden))
        { throw "SVG contains '$Forbidden', which UE's SVG rasterizer does not support: $SvgPath" }
    }
}

# Deterministic order regardless of manifest ordering.
$Icons = @($Manifest.icons | Sort-Object -Property semantic -CaseSensitive)

# ---------------------------------------------------------------------------------------------------------------------
# Emit
# ---------------------------------------------------------------------------------------------------------------------

$Banner = @(
    '// ====================================================================================================================',
    '// GENERATED FILE — DO NOT HAND-EDIT.',
    '// Generated by Source/CkScripts/Generate-CkIcons.ps1 from Resources/Icons/CkIcons_Manifest.json.',
    '// To add or change an icon: edit the manifest (and vendor the SVG via Import-MdiIcon.ps1), then regenerate.',
    '// ===================================================================================================================='
)

$H = [System.Collections.Generic.List[string]]::new()
$H.Add('#pragma once')
$H.Add('')
$Banner | ForEach-Object { $H.Add($_) }
$H.Add('')
$H.Add('#include "CkCore/Format/CkFormat.h"')
$H.Add('')
$H.Add('#include <CoreMinimal.h>')
$H.Add('')
$H.Add('#include "CkIcons_Generated.generated.h"')
$H.Add('')
$H.Add('// --------------------------------------------------------------------------------------------------------------------')
$H.Add('')
$H.Add('UENUM(BlueprintType)')
$H.Add('enum class ECk_Icon : uint8')
$H.Add('{')
foreach ($Entry in $Icons) { $H.Add("    $($Entry.semantic),") }
$H.Add('};')
$H.Add('')
$H.Add('CK_DEFINE_CUSTOM_FORMATTER_ENUM(ECk_Icon);')
$H.Add('')
$H.Add('// --------------------------------------------------------------------------------------------------------------------')
$H.Add('')
$H.Add('namespace ck::icons')
$H.Add('{')
$H.Add('    struct FGeneratedEntry')
$H.Add('    {')
$H.Add('        ECk_Icon Icon;')
$H.Add('        const TCHAR* SemanticName;')
$H.Add('        const TCHAR* RelativePath;')
$H.Add('    };')
$H.Add('')
$H.Add('    CKEDITORTOOLS_API auto Get_GeneratedEntries() -> TConstArrayView<FGeneratedEntry>;')
$H.Add('}')
$H.Add('')
$H.Add('// --------------------------------------------------------------------------------------------------------------------')

$C = [System.Collections.Generic.List[string]]::new()
$C.Add('#include "CkIcons_Generated.h"')
$C.Add('')
$Banner | ForEach-Object { $C.Add($_) }
$C.Add('')
$C.Add('namespace ck::icons')
$C.Add('{')
$C.Add('    auto')
$C.Add('        Get_GeneratedEntries()')
$C.Add('        -> TConstArrayView<FGeneratedEntry>')
$C.Add('    {')
$C.Add('        static const FGeneratedEntry Entries[] =')
$C.Add('        {')
foreach ($Entry in $Icons)
{
    $C.Add("            { ECk_Icon::$($Entry.semantic), TEXT(`"$($Entry.semantic)`"), TEXT(`"Mdi/$($Entry.mdi)`") },")
}
$C.Add('        };')
$C.Add('')
$C.Add('        return Entries;')
$C.Add('    }')
$C.Add('}')
$C.Add('')
$C.Add('// --------------------------------------------------------------------------------------------------------------------')

$HeaderText = ($H -join "`r`n") + "`r`n"
$CppText    = ($C -join "`r`n") + "`r`n"

$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)

if ($Check)
{
    $Drift = @()
    if (-not (Test-Path $OutHeader) -or ([System.IO.File]::ReadAllText($OutHeader) -cne $HeaderText)) { $Drift += $OutHeader }
    if (-not (Test-Path $OutCpp)    -or ([System.IO.File]::ReadAllText($OutCpp)    -cne $CppText))    { $Drift += $OutCpp }

    if ($Drift.Count -gt 0)
    {
        Write-Host "DRIFT: generated output does not match the manifest. Re-run Generate-CkIcons.ps1 and commit:" -ForegroundColor Red
        $Drift | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        exit 3
    }

    Write-Host "OK: generated output matches the manifest ($($Icons.Count) icons)."
    exit 0
}

[System.IO.File]::WriteAllText($OutHeader, $HeaderText, $Utf8NoBom)
[System.IO.File]::WriteAllText($OutCpp, $CppText, $Utf8NoBom)

Write-Host "Generated $($Icons.Count) icons:"
Write-Host "  $OutHeader"
Write-Host "  $OutCpp"
